---
booktitle: Proceedings of the Thirteenth International Conference on Artificial Intelligence
  and Statistics
month: 0
publisher: JMLR Workshop and Conference Proceedings
volume: 9
logoright: basic_files/SAIS_logo.jpg
year: '2010'
start: 2010-05-13
end: 2010-05-15
published: 2010-03-31
shortname: AISTATS 2010
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: TehAISTATS2010
abstract: ''
editor:
- given: Yee Whye
  family: Teh
- given: Mike
  family: Titterington
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Thirteenth International Conference on Artificial Intelligence and Statistics
    Held in Chia Laguna Resort, Sardinia, Italy on 13-15 May 2010

  Published as Volume 9 by the Proceedings of Machine Learning Research on 31 March 2010.

  Volume Edited by:
    Yee Whye Teh
    Mike Titterington

  Series Editors:
    Neil D. Lawrence
url: http://proceedings.mlr.press
baseurl: "/v9"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v9
email: ''
conference:
  name: Proceedings of the Thirteenth International Conference on Artificial Intelligence
    and Statistics
  url: 
  location: Chia Laguna Resort, Sardinia, Italy
  dates:
  - 2010-05-13
  - 2010-05-14
  - 2010-05-15
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v9.bib
